version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "alfupe"
    assignees:
      - "alfupe"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    automerge:
      - type: "patch"
        update-types: [ "version-update:semver-patch" ]