version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: build
      include: scope
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
      oxlint:
        patterns:
          - "oxlint*"
      prettier:
        patterns:
          - "prettier"
      testing:
        patterns:
          - "@yabbadabbadev/pepito"
          - "vitest-browser-react"
          - "@vitest/browser*"
          - "playwright"
          - "msw"
          - "vitest"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: build
      include: scope
    groups:
      actions:
        patterns:
          - "*"
