version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: build
      include: scope
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
      testing:
        patterns:
          - "@testing-library/*"
          - "vitest"
          - "jsdom"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: build
      include: scope
    groups:
      actions:
        patterns:
          - "*"
