name: PR checks

on:
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Read Node.js version from .nvmrc
              id: nvm
              run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

            - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test
